version: '3'
services:

  postgres:
    image: postgres:14-alpine

  redis:
    image: redis:6-alpine

  prometheus:
    image: prom/prometheus:main
    volumes:
      - ./prometheus:/etc/prometheus

  bot:
    build:
      context: .
    depends_on:
      - postgres
      - redis
